[profile.default]
failure-output = "immediate-final"
fail-fast = false

[profile.ci]
junit.path = "junit.xml"
failure-output = "immediate-final"
fail-fast = false

[profile.measure]
retries = 0
fail-fast = false
failure-output = "immediate-final"

[profile.measure.junit]
path = "junit.xml"

[profile.fast]
retries = 0
fail-fast = false
failure-output = "immediate-final"
